<a href="https://colab.research.google.com/github/sxddxrth/PPML-/blob/main/240901105%20Numpy%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVertor addition")
print(a+b)
print("\nVertor subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)
print("\nVector division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))
print("scalar multiplication")
sclr=5
print("Scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array 1:",arr1)
print("array 2:",arr2)
print("result:",vec_func(arr1,arr2))

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vertor addition
[12 24 35 48 60]

Vertor subtraction
[ 8 16 25 32 40]

Vector multiplication
[ 20  80 150 320 500]

Vector division
[5. 5. 6. 5. 5.]

Vector Dot product
1070
scalar multiplication
Scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]
array 1: [10, 4, 20]
array 2: [2, 3, 30]
result: [ 8  1 50]
